import type { Metadata } from 'next'
import { Ubuntu_Mono, Inter } from 'next/font/google'

import './globals.css'
import { Header } from '@/components/Layout/Header'
import Link from 'next/link'

const ubuntuMono = Ubuntu_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-ubuntu-mono',
  weight: ['400', '700'],
})

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
  weight: ['300', '400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${ubuntuMono.variable} ${inter.variable} relative`}>
        <Header />

        {children}

        <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6">
          <p className="text-xs text-zinc-500">&copy; 2024 Gaia Future Lab. Todos os direitos reservados.</p>
          <nav className="sm:ml-auto flex gap-4 sm:gap-6">
            {/* <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
              Termos de serviço
            </Link>
            <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
              Privacidade
            </Link> */}
          </nav>
        </footer>
      </body>
    </html>
  )
}
